#!/bin/bash

# Captive Portal Offline Installer
# Installs dependencies and configures the system without internet access

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SETUP_DIR="$(dirname "${BASH_SOURCE[0]}")"

echo -e "${BLUE}=======================================${NC}"
echo -e "${BLUE}  Captive Portal Offline Installer${NC}"
echo -e "${BLUE}=======================================${NC}\n"

if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}Error: Must run as root (sudo)${NC}"
   exit 1
fi

# 1. Install System Dependencies
echo -e "${YELLOW}[1/5]${NC} Installing system packages from local archive..."
if ls "$SETUP_DIR/deb/"*.deb 1> /dev/null 2>&1; then
    dpkg -i -R "$SETUP_DIR/deb/" || {
        echo -e "${YELLOW}Warning: dpkg returned error, attempting fix...${NC}"
        apt-get install -f -y || echo -e "${RED}Failed to fix dependencies${NC}"
    }
else
    echo -e "${YELLOW}No .deb packages found in setup/deb/${NC}"
    echo -e "${YELLOW}Skipping system package installation...${NC}"
fi

# 2. Install Python Dependencies
echo -e "\n${YELLOW}[2/5]${NC} Installing Python packages from local archive..."
if ls "$SETUP_DIR/pip_packages/"* 1> /dev/null 2>&1; then
    pip3 install --no-index --find-links="$SETUP_DIR/pip_packages" Flask mysql-connector-python psutil
else
    echo -e "${YELLOW}No Python packages found in setup/pip_packages/${NC}"
    echo -e "${YELLOW}Skipping Python package installation...${NC}"
fi

# 3. Generate Configuration Files
echo -e "\n${YELLOW}[3/5]${NC} Generating configuration files..."

# Generate config.sh
cat > "$PROJECT_ROOT/config.sh" <<EOF
#!/bin/bash
# Captive Portal Configuration
# Generated by offline installer

# Network Configuration
INTERFACE="wlan0"  # Will be auto-detected by configure.sh
STATIC_IP="192.168.4.1"
NETMASK="255.255.255.0"
DHCP_RANGE_START="192.168.4.2"
DHCP_RANGE_END="192.168.4.20"

# WiFi Hotspot Settings
SSID="CaptivePortal"
WPA_PASSPHRASE="portal123"
CHANNEL="7"

# Server Configuration
SERVER_PORT="80" 

# Database Configuration
MYSQL_USER="fungames"
MYSQL_PASSWORD="7396Ksn!"
MYSQL_DATABASE="fungames"
USER_ID="320"
SHOP_ID="1"
EOF
chmod +x "$PROJECT_ROOT/config.sh"
echo -e "  ${GREEN}✓${NC} generated config.sh"

# Generate hostapd.conf
cat > "$PROJECT_ROOT/hostapd.conf" <<EOF
interface=wlan0
driver=nl80211
ssid=CaptivePortal
hw_mode=g
channel=7
wmm_enabled=0
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=portal123
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
EOF
echo -e "  ${GREEN}✓${NC} generated hostapd.conf"

# Generate dnsmasq.conf
cat > "$PROJECT_ROOT/dnsmasq.conf" <<EOF
interface=wlan0
dhcp-range=192.168.4.2,192.168.4.20,12h
dhcp-option=3,192.168.4.1
dhcp-option=6,192.168.4.1
address=/#/192.168.4.1
EOF
echo -e "  ${GREEN}✓${NC} generated dnsmasq.conf"

# 4. Set Permissions
echo -e "\n${YELLOW}[4/5]${NC} Setting permissions..."
chmod +x "$PROJECT_ROOT/"*.sh
chmod +x "$PROJECT_ROOT/"*.py
echo -e "  ${GREEN}✓${NC} Scripts became executable"

# 5. Run Auto-Configuration
echo -e "\n${YELLOW}[5/5]${NC} Running auto-configuration..."
cd "$PROJECT_ROOT"
./configure.sh

# 6. Generate Device Fingerprint & License
echo -e "\n${YELLOW}[6/7]${NC} Generating device license..."

if [ -f "$PROJECT_ROOT/security/secgen.py" ]; then
    # Run the generator from its directory
    cd "$PROJECT_ROOT/security"
    python3 secgen.py
    
    if [ -f "dlI" ]; then
         echo -e "  ${GREEN}✓${NC} License generated (dlI)"
    else
         echo -e "  ${RED}✗ License generation failed${NC}"
    fi
    cd "$PROJECT_ROOT"
else
    echo -e "${YELLOW}Warning: secgen.py not found in security/${NC}"
fi

# 7. Lock Configurations
echo -e "\n${YELLOW}[7/7]${NC} Locking configuration files..."
if command -v chattr &> /dev/null; then
    chattr +i "$PROJECT_ROOT/config.sh"
    chattr +i "$PROJECT_ROOT/hostapd.conf"
    chattr +i "$PROJECT_ROOT/dnsmasq.conf"
    echo -e "  ${GREEN}✓${NC} Configuration files are now immutable (locked)"
else
    echo -e "${YELLOW}Warning: chattr command not found, skipping file locking${NC}"
fi

echo -e "\n${BLUE}=======================================${NC}"
echo -e "${GREEN}✓ Setup Complete!${NC}"
echo -e "${BLUE}=======================================${NC}"
echo -e "To start the portal: ${YELLOW}sudo ./start.sh${NC}"
