#!/bin/bash
# Captive Portal Configuration
# Generated by offline installer

# Network Configuration
INTERFACE="wlan0"  # Will be auto-detected by configure.sh
STATIC_IP="192.168.4.1"
NETMASK="255.255.255.0"
DHCP_RANGE_START="192.168.4.2"
DHCP_RANGE_END="192.168.4.20"

# WiFi Hotspot Settings
SSID="CaptivePortal"
WPA_PASSPHRASE="portal123"
CHANNEL="7"

# Server Configuration
SERVER_PORT="80" 

# Database Configuration
MYSQL_USER="fungames"
MYSQL_PASSWORD="7396Ksn!"
MYSQL_DATABASE="fungames"
USER_ID="320"
SHOP_ID="1"
